// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/rotemtam/ent-blog-example/ent/runtime.go

const (
	Version = "v0.12.4-0.20230523115418-d7b3a6c4f4dc"           // Version of ent codegen.
	Sum     = "h1:4PirMskvwZ8fl6MsQyXUXQaGQUUad6dvARykGwWR5QY=" // Sum of ent codegen.
)
